// Plain-text body for the management agreement. Lives next to the
// schema so the same paragraphs render in both the owner sign page
// (HTML) and the signed PDF (React-PDF). Keeping it as structured
// data rather than a hand-formatted blob means we can swap in
// translations or a country-specific clause set later without
// rewriting the renderer.
//
// IMPORTANT: do not edit terms here that appear on the form. The
// commercial terms (term length, commission, exit fee, notice) come
// from the snapshotted ManagementAgreement row, not from this file.
// Anything templated in {curly braces} is filled at render time.

export type AgreementSection = {
  heading: string;
  body: string[]; // paragraphs; rendered with blank line between
};

export type AgreementContext = {
  ownerName: string;
  ownerCompany: string | null;
  propertyName: string;
  propertyAddress: string;
  propertyCity: string;
  governingLaw: string;
  termMonths: number;
  commissionPct: string; // already formatted, e.g. "20%"
  earlyExitFeeFormatted: string; // e.g. "KES 75,000"
  noticePeriodDays: number;
  isShortTerm: boolean;
};

export function buildAgreementSections(ctx: AgreementContext): AgreementSection[] {
  const ownerLabel = ctx.ownerCompany
    ? `${ctx.ownerCompany} (acting through ${ctx.ownerName})`
    : ctx.ownerName;

  const serviceLine = ctx.isShortTerm
    ? "marketing the Property on Airbnb and other approved short-stay channels, vetting guests, coordinating cleaning and turnover, handling guest communication, and remitting net payouts to the Owner each calendar month."
    : "sourcing and vetting tenants, drafting tenancy agreements on the Owner's behalf, collecting monthly rent, managing routine maintenance requests, and remitting net rent to the Owner each calendar month.";

  return [
    {
      heading: "1. Parties",
      body: [
        `This Property Management Agreement ("Agreement") is entered into between Goldstay Limited ("Goldstay") and ${ownerLabel} ("Owner") in respect of the property at ${ctx.propertyAddress}, ${ctx.propertyCity} ("Property").`,
      ],
    },
    {
      heading: "2. Services",
      body: [
        `Goldstay will act as the Owner's exclusive managing agent for the Property. Services include ${serviceLine}`,
        "Goldstay will provide the Owner with monthly statements detailing all inflows, outflows, and the resulting net payout, downloadable from the Owner's Goldstay portal.",
      ],
    },
    {
      heading: "3. Term and renewal",
      body: [
        `This Agreement is for an initial term of ${ctx.termMonths} months from the Effective Date. At the end of the initial term it renews automatically for successive twelve-month periods unless either party gives written notice of non-renewal at least ${ctx.noticePeriodDays} days before the end of the then-current term.`,
      ],
    },
    {
      heading: "4. Commission",
      body: [
        `In consideration for the Services, the Owner agrees to pay Goldstay a management commission of ${ctx.commissionPct} of gross income generated by the Property (rent for long-term lettings; gross booking revenue net of OTA fees for short-term stays). Goldstay deducts its commission from amounts collected before remitting the balance to the Owner.`,
        "Out-of-pocket expenses (cleaning, repairs, statutory fees) are passed through at cost and itemised on the monthly statement.",
      ],
    },
    {
      heading: "5. Owner's responsibilities",
      body: [
        "The Owner warrants that they have full title or authority to let the Property and that all required consents (including spousal consent where applicable) have been obtained.",
        "The Owner is responsible for property taxes, insurance covering loss of rent and public liability, and any structural maintenance not arising from ordinary wear-and-tear.",
      ],
    },
    {
      heading: "6. Goldstay's responsibilities",
      body: [
        "Goldstay will hold all rental and booking revenue in a clearly identifiable client trust arrangement until remittance.",
        "Goldstay will exercise reasonable skill and care in the discharge of its duties and will not act outside the scope of this Agreement without the Owner's prior written consent.",
      ],
    },
    {
      heading: "7. Early termination",
      body: [
        `Either party may terminate this Agreement before the end of the initial term by giving the other party at least ${ctx.noticePeriodDays} days written notice. If the Owner terminates before the end of the initial term other than for Goldstay's material breach, the Owner will pay Goldstay an early-exit fee of ${ctx.earlyExitFeeFormatted} to recover the up-front investment in onboarding, photography, listing optimisation and channel setup.`,
        "No early-exit fee is payable where Goldstay terminates without cause, where termination is for Goldstay's material breach, or where the Property becomes legally untenantable through no fault of the Owner.",
      ],
    },
    {
      heading: "8. Payouts and reconciliation",
      body: [
        "Goldstay will remit the Owner's share by the 10th of the calendar month following the month of collection. Statements are reconciled to the underlying bookings or lease and are auditable through the Goldstay portal for at least 24 months after generation.",
      ],
    },
    {
      heading: "9. Confidentiality and data",
      body: [
        "Each party will keep confidential information disclosed under this Agreement confidential. Personal data of guests and tenants will be handled in accordance with applicable data-protection law in the governing jurisdiction.",
      ],
    },
    {
      heading: "10. Governing law",
      body: [
        `This Agreement is governed by the laws of ${ctx.governingLaw} and the parties submit to the exclusive jurisdiction of the courts of ${ctx.governingLaw}.`,
      ],
    },
    {
      heading: "11. Entire agreement",
      body: [
        "This Agreement constitutes the entire agreement between the parties on its subject matter and supersedes all prior discussions or arrangements. Variations must be in writing and signed by both parties.",
      ],
    },
  ];
}
